[package]
name = "zkmr-client"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json.workspace = true
wasm-bindgen.workspace = true
web-sys.workspace = true
zkmr-types = { path = "../types" }
